CREATE TYPE stock_exchange AS ENUM (
    'NASDAQ', 'NYSE', 'HKEX', 'SSE', 'SZSE', 'LSE', 'JPX', 'KRX', 'TSX', 'FWB', 'OTHER'
);

CREATE TYPE stock_status AS ENUM ('active', 'delisted', 'suspended');

CREATE TABLE stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exchange stock_exchange NOT NULL,
    ticker TEXT NOT NULL,
    symbol TEXT NOT NULL,
    company_name TEXT NOT NULL,
    short_name TEXT,
    ipo_date DATE,
    delist_date DATE,
    status stock_status NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (exchange, ticker)
);

-- 自动补齐港股ticker 触发器，示例
CREATE OR REPLACE FUNCTION stocks_ticker_format() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.exchange = 'HKEX' THEN
        NEW.ticker := LPAD(NEW.ticker, 5, '0');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_stocks_ticker_format
BEFORE INSERT OR UPDATE ON stocks
FOR EACH ROW EXECUTE FUNCTION stocks_ticker_format();

-- 自动生成 symbol
CREATE OR REPLACE FUNCTION generate_symbol() RETURNS TRIGGER AS $$
BEGIN
  NEW.symbol := NEW.exchange || ':' || NEW.ticker;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_generate_symbol
BEFORE INSERT OR UPDATE ON stocks
FOR EACH ROW EXECUTE FUNCTION generate_symbol();

-- 更新时间戳
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = now();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_update_updated_at
BEFORE UPDATE ON stocks
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
